export const workExperience = [
    {
      icon: "S",
      company: "Sewantika",
      role: "Javascript, Ejs, DoM , SCSS",
      shortdesc:
        "Landing page for a project",
      desc: " A holistic solution for all problemn related to complete product developemt from ideation, curation, fabrication to market delivery.",
      bgColor: "bg-purple-600",
      textColor: "text-white",
      sourceCode: "",
      webLink: "https://www.sewantika.com/",
    },
    {
      icon: "I",
      company: "Intruder Detection",
      role: "OpenCV, Python",
      shortdesc: "Motion detection using matrix difference",
      desc: "A Python-based motion detection script using OpenCV designed for security systems. The script captures video from the webcam, detects motion, and triggers an audible alarm when motion is detected.",
      bgColor: "bg-green-500",
      textColor: "text-slate-100",
      sourceCode: "https://github.com/Asta1984/Motion-Detection-using-openCV.git",
      webLink: "",
    },
    {
      icon: "P",
      company: "Mordern Perodic table",
      role: "HTML, CSS, Javascript, githubActions",
      shortdesc: "My first web development project",
      desc: "The idea was simple I could not remember the periodic table at school which push me to learn web dev and built this project.",
      bgColor: "bg-black",
      textColor: "text-white",
      sourceCode: "https://github.com/Asta1984/Periodic-table.git",
      webLink: "https://asta1984.github.io/Periodic-table/",
    },
    {
      icon: "G",
      company: "GangChat",
      role: "Javascript, React, Firebase",
      shortdesc: "A chatroom for close group of friends.",
      desc: "A custom chatroom with firebase backend, authentication and without using web sockets.",
      bgColor: "bg-orange-600",
      textColor: "text-white",
      sourceCode: "https://github.com/Asta1984/gangCHAT.git",
      webLink: "https://gang-chat.vercel.app/",
    },
    {
      icon: "A",
      company: "Autonomous Bot",
      role: "Embedded C, Data stuctures, Arduino",
      shortdesc: "An autonoumous navigating bot.",
      desc: "Developed and designed a bot capable of multi-terrain operation with 4 degree of freedom uses different sensor fusion to get surrounding data to create 3-D mappings.",
      bgColor: "bg-green-500",
      textColor: "text-white",
      sourceCode: "https://drive.google.com/drive/folders/1JuOScmxXXVIyU6GKKZA9AB_qh4qN3A68",
      webLink: "",
    },
    {
      icon: "T",
      company: "Vehicle Side Profiling",
      role: "Python, Flask, Networking Protocols",
      shortdesc: "Create side profiles of moving vehicles.",
      desc: "This project involved generation of side profile of vehicle while it's passing through a beam of sensor.",
      bgColor: "bg-red-600",
      textColor: "text-white",
      sourceCode: "",
      webLink: "https://portfolio-website-five-amber.vercel.app/#portfolio",
    },
  ];